In [489]:
import numpy as np
import pandas as pd
import csv
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [490]:
#Importing the raw data 
file = open('hw1_q2_dataset.csv')
csvreader = csv.reader(file, delimiter = ",")
data = []
for row in csvreader:
    data.append(row)

program_data = []
for i in range(0 , len(data)):
    col= []
    for j in range(0,len(data[i])):
        if j==len(data[i])-1:
            col.append(data[i][j])
        else:
            col.append(float(data[i][j]))
    program_data.append(col)
file.close()

In [491]:
#Now we have the program data with us successfully now we will seprate it into training and test data set as per
#Given Conditions
test_data = []
train_data = []
c = 0
p = 0
m = 0
k = 0
for i in range(0,len(program_data)):
    
    if(program_data[i][4]==' Ceramic' and c<6):
        c=c+1
        test_data.append(program_data[i])
    if(program_data[i][4]==' Plastic' and p<6):
        p=p+1
        test_data.append(program_data[i])
    if(program_data[i][4]==' Metal' and m<6):
        m=m+1
        test_data.append(program_data[i])
    if(p>=6 and c>=6 and m>=6):
            train_data.append(program_data[i])

In [492]:
#Now we have successfully done with our training and test data now we will replace the classes of plastic with 
# 1 and all the other classes with -1 in order to perform svm

for i in range (0, len(train_data)):
    if(train_data[i][4]==' Plastic'):
        train_data[i][4]=0
    elif(train_data[i][4]==' Metal'):
        train_data[i][4]=1
    elif(train_data[i][4]==' Ceramic'):
        train_data[i][4]=2
for i in range (0, len(test_data)):
    if(test_data[i][4]==' Plastic'):
        test_data[i][4]=0
    elif(test_data[i][4]==' Metal'):
        test_data[i][4]=1
    elif(test_data[i][4]==' Ceramic'):
        test_data[i][4]=2


In [493]:
#We have converted the given raw datasets into dataframes uisng pandas 
column_names = ["Height","Diameter","Weight","Hue","Target"]
train_df = pd.DataFrame(data=train_data , columns =column_names)
test_df = pd.DataFrame(data = test_data, columns = column_names)


In [494]:
#Now we are seprating the traget value
X_train = train_df.drop(['Target'],axis = 'columns')
Y_train = train_df.Target
X_test = test_df.drop(['Target'],axis = 'columns')
Y_test = test_df.Target


In [495]:
X_train = X_train.to_numpy()
Y_train = Y_train.to_numpy()
X_test = X_test.to_numpy()
Y_test = Y_test.to_numpy()


In [496]:
clf = DecisionTreeClassifier(max_depth = len(X_train))

In [497]:
clf.fit(X_train,Y_train)

DecisionTreeClassifier(max_depth=102)

In [498]:
v = clf.predict(X_test)
print(v)
print(Y_test)

[2 1 0 0 0 0 0 0 0 1 0 0 0 1 0 2 2 2]
[2 1 2 2 0 0 0 0 0 0 2 1 1 1 1 1 2 2]


# Tree Classifier for full maximum Depth 

In [499]:
clf = DecisionTree(max_depth=100)

In [500]:
clf.fit(X_train,Y_train)

In [501]:
y_predict = clf.predict(X_test)
y_train_predict = clf.predict(X_train)

In [502]:
print(y_predict)
print(Y_test)

print("Confusion Matrix on Test Data \n")
print(confusion_matrix(Y_test,y_predict))
print(classification_report(Y_test,y_predict))
print("Confusion Matrix on Train Data \n")
print(confusion_matrix(Y_train,y_train_predict))
print(classification_report(Y_train,y_train_predict))

[2 1 0 2 0 1 0 0 0 0 0 0 1 1 1 0 1 2]
[2 1 2 2 0 0 0 0 0 0 2 1 1 1 1 1 2 2]
Confusion Matrix on Test Data 

[[5 1 0]
 [2 4 0]
 [2 1 3]]
              precision    recall  f1-score   support

           0       0.56      0.83      0.67         6
           1       0.67      0.67      0.67         6
           2       1.00      0.50      0.67         6

    accuracy                           0.67        18
   macro avg       0.74      0.67      0.67        18
weighted avg       0.74      0.67      0.67        18

Confusion Matrix on Train Data 

[[53  0  0]
 [ 0 24  0]
 [ 0  0 25]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        53
           1       1.00      1.00      1.00        24
           2       1.00      1.00      1.00        25

    accuracy                           1.00       102
   macro avg       1.00      1.00      1.00       102
weighted avg       1.00      1.00      1.00       102



# Observation Q3_2 

As we can see it is overfitting and thus we only get accuracy of 56% only where as it has 100% accuracy in training dataset

# Tree Classifier with different depths

In [503]:
for i in range(1,7):
    clf = DecisionTree(max_depth = i)
    clf.fit(X_train,Y_train)
    y_predict = clf.predict(X_test)
    print("The accuracy for depth %d is",i)
    print(accuracy(y_predict,Y_test))
    y_p_t = clf.predict(X_train)
    print("The training accuracy for depth %d is",i)
    print(accuracy(y_p_t,Y_train))

The accuracy for depth %d is 1
33.33333333333333
The training accuracy for depth %d is 1
51.9607843137255
The accuracy for depth %d is 2
27.77777777777778
The training accuracy for depth %d is 2
65.68627450980392
The accuracy for depth %d is 3
44.44444444444444
The training accuracy for depth %d is 3
67.64705882352942
The accuracy for depth %d is 4
38.88888888888889
The training accuracy for depth %d is 4
75.49019607843137
The accuracy for depth %d is 5
44.44444444444444
The training accuracy for depth %d is 5
79.41176470588235
The accuracy for depth %d is 6
38.88888888888889
The training accuracy for depth %d is 6
81.37254901960785


# Observation Q3_3 

Thus from the above observation we can say that depth 4 , depth 5 and depth 6 comes under overfitting